data_params:
  root_dir: dataset/Emotic/
  transform: True
  out_class: 26
  

images:
  in_channels: 3
  context_mean: [0.4695, 0.4411, 0.4055]
  context_std: [0.2830, 0.2760, 0.2829]
  body_mean: [0.4388, 0.3969, 0.3711]
  body_std: [0.2860, 0.2726, 0.2730]

train_params:
  num_epochs: 100
  batch_size: 32
  num_workers: 5
  lr: 0.005
  epoch_milestones: [60, 80]

